// API documents - now can be generated by AI

const swaggerJSdoc = require('swagger-jsdoc');

const options = {
    definition: {
        openapi: "3.0.0",
        info: {
            title: "Movie API",
            version: "0.0.1",
            description: "This is a simple Movie API doc",
        },
        servers: [
            {
                url: "http://localhost:4000",
                description: "Development server",
            }
        ]
    },
    // Path to the API docs in controllers
    apis: ["./src/controllers/*.js"],
};

module.exports = swaggerJSdoc(options);